configfile: "config/config.yaml"

SAMPLE = config["sample"]
REF = config["reference"]

rule all:
    input:
        expand("results/report/{sample}_report.pdf", sample=SAMPLE),
        expand("results/fastqc/{sample}_R1_001_fastqc.html", sample=SAMPLE),
        expand("results/fastqc/{sample}_R2_001_fastqc.html", sample=SAMPLE)

rule fastqc:
    input:
        r1="samples/{sample}_R1_001.fastq.gz",
        r2="samples/{sample}_R2_001.fastq.gz"
    output:
        html1="results/fastqc/{sample}_R1_001_fastqc.html",
        zip1="results/fastqc/{sample}_R1_001_fastqc.zip",
        html2="results/fastqc/{sample}_R2_001_fastqc.html",
        zip2="results/fastqc/{sample}_R2_001_fastqc.zip"
    shell:
        """
        mkdir -p results/qc
        fastqc {input.r1} {input.r2} -o results/fastqc
        """

rule fastp:
    input:
        r1="samples/{sample}_R1_001.fastq.gz",
        r2="samples/{sample}_R2_001.fastq.gz"
    output:
        r1="results/trimmed/{sample}_R1.trim.fastq.gz",
        r2="results/trimmed/{sample}_R2.trim.fastq.gz"
    shell:
        """
        mkdir -p results/trimmed
        fastp \
          -i {input.r1} \
          -I {input.r2} \
          -o {output.r1} \
          -O {output.r2}
        """

rule bwa:
    input:
        r1="results/trimmed/{sample}_R1.trim.fastq.gz",
        r2="results/trimmed/{sample}_R2.trim.fastq.gz",
        ref=REF
    output:
        bam="results/bam/{sample}.sorted.bam"
    threads:
        config["threads"]
    shell:
        """
        mkdir -p results/bam

        bwa mem -t {threads} {input.ref} \
        {input.r1} {input.r2} | \
        samtools sort -o {output.bam}

        samtools index {output.bam}
        """

rule variant_calling:
    input:
        bam="results/bam/{sample}.sorted.bam",
        ref=REF
    output:
        vcf="results/vcf/{sample}.vcf.gz"
    threads: 12

    shell:
        """
        mkdir -p results/vcf

        bcftools mpileup \
        -Ou \
        -f {input.ref} \
        {input.bam} | \
        bcftools call \
        --threads {threads} \
        -mv \
        -Oz \
        -o {output.vcf}

        tabix -p vcf {output.vcf}
        """

rule pgx_filter:
    input:
        vcf="results/vcf/{sample}.vcf.gz",
        bed="resources/pgx_genes.bed"
    output:
        "results/pgx/{sample}.pgx.vcf"
    shell:
        """
        mkdir -p results/pgx

        bedtools intersect \
            -header \
            -a {input.vcf} \
            -b {input.bed} \
            > {output}
        """

rule parse_pgx:
    input:
        vcf="results/pgx/{sample}.pgx.vcf",
        bed="resources/pgx_genes.bed"
    output:
        "results/pgx/{sample}_pgx_variants.tsv"
    shell:
        """
        mkdir -p results/pgx

        python scripts/parse_vcf.py \
        {input.vcf} \
        {input.bed} \
        {output}
        """

rule drug_annotation:
    input:
        variants="results/pgx/{sample}_pgx_variants.tsv",
        gene_info_path="resources/gene_info.tsv",
        guidelines_path="resources/drug_guidelines.tsv"

    output:
        phenotypes_out="results/pgx/{sample}_phenotypes.tsv",
        drug_recs_out="results/pgx/{sample}_drug_recommendations.tsv",
    shell:
        """
        mkdir -p results/report

        python scripts/assign_phenotypes.py \
        {input.variants} \
        {input.gene_info_path} \
        {input.guidelines_path} \
        {output.phenotypes_out}\
        {output.drug_recs_out}\
        """

rule report:
    input:
        metadata="samples/{sample}_metadata.tsv",
        phenotypes="results/pgx/{sample}_phenotypes.tsv",
        drugs="results/pgx/{sample}_drug_recommendations.tsv",
        variants="results/pgx/{sample}_pgx_variants.tsv"
    output:
        "results/report/{sample}_report.pdf"
    shell:
        """
        mkdir -p results/report

        python scripts/generate_report.py \
        {input.metadata} \
        {input.phenotypes} \
        {input.drugs} \
        {input.variants} \
        {output}
        """